### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by ramnathv** [nijikokun/clarity#1]
I really like this theme. But, I would like to use a different syntax highlighting theme and fonts. Is there a simple way to swap out `highlightjs` syntax highlighting themes and fonts?

**Comment by ramnathv** [comment]
I figured out the reason why the `tomorrow` theme is getting overridden. The `markdown.less` file adds a blue background to `pre` blocks. I modified `markdown.less` to take out these lines and used `grunt build` to rebuild the styles. But, when I tried to use them as a theme, the `fontawesome` files are not getting picked up. Any hints on what might be happening. I am new to `grunt` and `npm`, so might be doing something really elementary.

**Comment by nijikokun** [comment]
Thank you, the easiest way is to just modify the stylesheets, I'll probably create a list of around 40 themes, and let you choose in a JS file or through the builder.

As far as not picking up the fonts, can you tell me what lines you removed?

**Comment by ramnathv** [comment]
I removed [these lines](https://github.com/Nijikokun/clarity/blob/master/lib/stylesheets/book/markdown.less#L277-L299). But I don't think that is the issue. The problem is when I do `grunt build` after the change, the `style.css` does not pick up `fontawesome` fonts correctly.
