### ISSUE TITLE
Using arrow keys to navigate deletes state

### ISSUE THREAD

**Issue by ramnathv** [nijikokun/clarity#2]
When I use arrow keys to navigate, the checkmarks against completed chapters disappear. I suspect it is some kind of a bug?

**Comment by nijikokun** [comment]
It sure is, I'll look into this when I have a chance, it probably has to deal with me not calling a progress method correctly, or I need to re-adjust the progress.js method slightly to support pjax

**Comment by nijikokun** [comment]
Can you check the latest commits to see if they fix your issue?

**Comment by ramnathv** [comment]
I pulled your latest commit, but this time `fontawesome` is broken even without me running the `grunt` task. Let me make sure I am doing this correctly. Here is what I did

``` bash
$ hub clone Nijikokun/clarity
$ npm install
$ npm build
```

And then in my `gitbook` repo, I just ran

``` bash
$ gitbook serve -g user/repo --theme=path/to/clarity/lib
```

When I did this earlier, everything worked EXCEPT for the chapter checkmarks. But now, I can't see any icon fonts as a result of which I am unable to confirm whether the checkmarks are fixed or not.

Let me know if you need more information to understand the situation.

**Comment by nijikokun** [comment]
This seems to be a problem with how gitbook is serving things rather than the theme.

**Comment by ramnathv** [comment]
I tried to just build using `gitbook` and then use `python -m SimpleHTTPServer` to serve. I am getting the same error. Here is the error message in my console

```
Failed to load resource: the server responded with a status of 404 (File not found) http://localhost:8000/fonts/fontawesome/fontawesome-webfont.svg
```

My directory structure is thus

```
|- book
|- clarity
```

For some reason, the path to the font folder is reverting to the root, rather than relative to `style.css`.

**Comment by nijikokun** [comment]
I've pushed a fix, this is a gitbook issue, instead of serving them from the root of the book at `fonts/` they are serving them under a folder called `gitbook`

**Comment by ramnathv** [comment]
You are right. Thanks. It works now. This theme is really very `zen` and thanks for your prompt responses. I hope to use this very soon.
